services:
  bootstrap:
    build:
      context: .
      dockerfile: Dockerfile.bootstrap
    container_name: bootstrap
    networks:
      p2p-network:
        ipv4_address: 172.20.0.2
    ports:
      - "6881:6881/tcp"
      - "6881:6881/udp"
      - "7881:7881/tcp"
      - "7881:7881/udp"
    restart: unless-stopped
    volumes:
      - ./bootstrap_data:/app/data
    environment:
      - GOSSIP_HOST=172.20.0.2

  client1:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: client1
    networks:
      p2p-network:
        ipv4_address: 172.20.0.3
    ports:
      - "6882:6881/tcp"
      - "6882:6881/udp"
      - "7882:7881/tcp"
      - "7882:7881/udp"
    volumes:
      - ./docker_directories/client1_torrents:/app/torrents
      - ./docker_directories/client1_downloads:/app/downloads
      - ./docker_directories/client1_data:/app/data
    restart: unless-stopped
    depends_on:
      - bootstrap
    stdin_open: true  # Keep STDIN open
    tty: true         # Allocate a pseudo-TTY
    command: ["6881"]
    environment:
      - GOSSIP_HOST=172.20.0.3

  client2:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: client2
    networks:
      p2p-network:
        ipv4_address: 172.20.0.4
    ports:
      - "6883:6881/tcp"
      - "6883:6881/udp"
      - "7883:7881/tcp"
      - "7883:7881/udp"
    volumes:
      - ./docker_directories/client2_torrents:/app/torrents
      - ./docker_directories/client2_downloads:/app/downloads
      - ./docker_directories/client2_data:/app/data
    restart: unless-stopped
    depends_on:
      - bootstrap
    stdin_open: true  # Keep STDIN open
    tty: true         # Allocate a pseudo-TTY
    command: ["6881"]
    environment:
      - GOSSIP_HOST=172.20.0.4

  client3:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: client3
    networks:
      p2p-network:
        ipv4_address: 172.20.0.5
    ports:
      - "6884:6881/tcp"
      - "6884:6881/udp"
      - "7884:7881/tcp"
      - "7884:7881/udp"
    volumes:
      - ./docker_directories/client3_torrents:/app/torrents
      - ./docker_directories/client3_downloads:/app/downloads
      - ./docker_directories/client3_data:/app/data
    restart: unless-stopped
    depends_on:
      - bootstrap
    stdin_open: true  # Keep STDIN open
    tty: true         # Allocate a pseudo-TTY
    command: ["6881"]
    environment:
      - GOSSIP_HOST=172.20.0.5

networks:
  p2p-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16