services:
  bootstrap:
    build:
      context: .
      dockerfile: Dockerfile.bootstrap
    ports:
      - "6881:6881/tcp"
      - "6881:6881/udp"
      - "7881:7881/tcp"
      - "7881:7881/udp"
    restart: unless-stopped
    networks:
      - p2p-network

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "6881:6881/tcp"
      - "6881:6881/udp"
      - "7881:7881/tcp"
      - "7881:7881/udp"
    volumes:
      - ./torrents:/app/torrents
      - ./downloads:/app/downloads
    restart: unless-stopped
    depends_on:
      - bootstrap
    networks:
      - p2p-network
    command: ["--port", "6882", "--connect", "bootstrap:6881"]

networks:
  p2p-network:
    driver: bridge